# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_inform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceobject',
            name='serial_number',
            field=models.CharField(default='ss', max_length=16, verbose_name='取货号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceobject',
            name='trouble',
            field=models.TextField(blank=True, verbose_name='遇到的问题'),
        ),
    ]
