# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-03 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_inform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceobject',
            name='flag',
            field=models.CharField(choices=[('完成', '完成'), ('修理中', '修理中'), ('已取回', '已取回'), ('遇到问题需反馈', '遇到问题需反馈'), ('待确认', '待确认')], max_length=64, verbose_name='修理状态'),
        ),
    ]
