# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_inform', '0002_auto_20161107_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='短信回复内容')),
                ('reply_time', models.DateTimeField(verbose_name='回复短信时间')),
                ('service_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_feedback', to='service_inform.ServiceObject', verbose_name='从属哪个服务对象')),
            ],
            options={
                'verbose_name': '短信回复',
                'verbose_name_plural': '短信回复',
            },
        ),
    ]
