# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('tel', models.CharField(max_length=11, verbose_name='电话')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=16, verbose_name='性别')),
                ('email', models.EmailField(blank=True, max_length=64, verbose_name='邮箱')),
                ('college', models.CharField(blank=True, max_length=64, verbose_name='学院-年级')),
                ('info', models.TextField(blank=True, verbose_name='其他')),
            ],
            options={
                'verbose_name': '成员',
                'verbose_name_plural': '成员',
            },
        ),
        migrations.CreateModel(
            name='ServiceActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField(auto_now_add=True, verbose_name='活动日期')),
                ('place', models.CharField(max_length=128, verbose_name='地点')),
                ('flag', models.CharField(choices=[('进行中', '进行中'), ('已完成', '已完成')], max_length=16, verbose_name='状态')),
                ('int_id', models.IntegerField(verbose_name='第几次活动')),
                ('members', models.ManyToManyField(blank=True, related_name='activities', to='service_activity.Member', verbose_name='成员')),
            ],
        ),
    ]
