# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceactivity',
            options={'verbose_name': '维修活动', 'verbose_name_plural': '维修活动'},
        ),
    ]
