# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-03 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceactivity',
            name='activity_date',
            field=models.DateField(verbose_name='活动日期'),
        ),
        migrations.AlterField(
            model_name='serviceactivity',
            name='flag',
            field=models.CharField(choices=[('进行中', '进行中'), ('已完成', '已完成'), ('预约中', '预约中')], max_length=16, verbose_name='状态'),
        ),
    ]
