# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_activity', '0002_auto_20161107_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceactivity',
            name='responsible_email',
            field=models.EmailField(blank=True, max_length=128, verbose_name='活动负责人邮箱'),
        ),
    ]
